import { z } from 'zod'

export const createProductSchema = z.object({
  sku: z.string().min(1),
  nameLat: z.string().min(1),
  nameCyr: z.string().optional(),
  brandId: z.string().optional(),
  brand: z.string().optional(),
  productLineId: z.string().optional(),
  productLine: z.string().optional(),
  categoryId: z.string().optional(),
  category: z.string().optional(),
  subCategory: z.string().optional(),
  description: z.string().optional(),
  benefits: z.string().optional(),
  ingredients: z.string().optional(),
  declaration: z.string().optional(),
  usageInstructions: z.string().optional(),
  priceB2c: z.coerce.number().positive(),
  priceB2b: z.coerce.number().positive().optional(),
  oldPrice: z.coerce.number().positive().optional(),
  costPrice: z.coerce.number().positive().optional(),
  stockQuantity: z.coerce.number().int().min(0).default(0),
  isProfessional: z.boolean().default(false),
  isNew: z.boolean().default(false),
  isFeatured: z.boolean().default(false),
  barcode: z.string().optional(),
  vatRate: z.coerce.number().int().min(0).max(100).default(20),
  vatCode: z.string().optional(),
  erpId: z.string().optional(),
})

// String fields where the admin form sends `null` to clear the value.
// All are `String?` in the Prisma schema, so null is valid downstream.
const nullableString = () => z.string().nullable().optional()

export const updateProductSchema = z.object({
  nameLat: z.string().min(1).optional(),
  nameCyr: nullableString(),
  brandId: nullableString(),
  brand: nullableString(),
  productLineId: nullableString(),
  productLine: nullableString(),
  categoryId: nullableString(),
  category: nullableString(),
  subCategory: nullableString(),
  description: nullableString(),
  benefits: nullableString(),
  ingredients: nullableString(),
  declaration: nullableString(),
  usageInstructions: nullableString(),
  priceB2c: z.coerce.number().positive().optional(),
  priceB2b: z.coerce.number().positive().optional().nullable(),
  oldPrice: z.coerce.number().positive().optional().nullable(),
  costPrice: z.coerce.number().positive().optional().nullable(),
  stockQuantity: z.coerce.number().int().min(0).optional(),
  lowStockThreshold: z.coerce.number().int().min(0).optional(),
  weightGrams: z.coerce.number().min(0).optional().nullable(),
  volumeMl: z.coerce.number().min(0).optional().nullable(),
  isProfessional: z.boolean().optional(),
  isNew: z.boolean().optional(),
  isFeatured: z.boolean().optional(),
  isBestseller: z.boolean().optional(),
  isActive: z.boolean().optional(),
  barcode: nullableString(),
  vatRate: z.coerce.number().int().min(0).max(100).optional(),
  vatCode: nullableString(),
  erpId: nullableString(),
  seoTitle: nullableString(),
  seoDescription: nullableString(),
  colorLevel: z.number().int().min(1).max(10).optional(),
  undertoneCode: z.string().optional(),
  undertoneName: z.string().optional(),
  hexValue: z.string().optional(),
  shadeCode: z.string().optional(),
  removeColor: z.boolean().optional(),
})

export const productFilterSchema = z.object({
  category: z.string().optional(),
  brand: z.union([z.string(), z.array(z.string())]).optional(),
  priceMin: z.coerce.number().optional(),
  priceMax: z.coerce.number().optional(),
  search: z.string().optional(),
  sort: z.enum(['popular', 'price_asc', 'price_desc', 'newest', 'rating']).default('popular'),
  isProfessional: z.coerce.boolean().optional(),
  isNew: z.coerce.boolean().optional(),
  onSale: z.coerce.boolean().optional(),
})
